- name: Provision ubuntu server for Acceptance Testing
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - { role: packages, tags: ['packages'] }
    - { role: nodejs, tags: ['nodejs'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: tty, tags: ['tty'] }
    # - { role: fitnesse, tags: ['fitnesse'] }
  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: reload systemd
      become: yes
      command: systemctl daemon-reload