- name: Provision ubuntu server for Fitnesse Acceptance Testing
  hosts: all
  become: yes
  become_method: sudo
  roles:
    # - { role: fitnesse, tags: ['fitnesse'] }
  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: reload systemd
      become: yes
      command: systemctl daemon-reload