- name: create phantomjs service
  template:
    src: templates/phantomjsdemo.service
    dest: /etc/systemd/system/phantomjsdemo.service
    owner:  root
    mode: 0755

- name: enable phantomjs as systemd service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: phantomjsdemo.service
  notify: reload systemd


- name: create web-terminal service
  template:
    src: templates/webterminaldemo.service
    dest: /etc/systemd/system/webterminaldemo.service
    owner: root
    mode: 0755

- name: enable web-terminal as systemd service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: restarted
    name: webterminaldemo.service
  notify: reload systemd

- name: put makefile in root directory
  template:
    src: templates/makefile
    dest: /
    owner: root
    mode: 0755
